service: will

frameworkVersion: '2.54.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./files/**

functions:
  telegram:
    handler: bin/telegram
    events:
      - http:
          path: telegram
          method: post